#!/usr/bin/env bash

# kernel-gen.sh — assemble ~/.claude/solar/SOLAR.md from kernel/ fragments
# per the selected components, render {{VAR}} placeholders, and write the
# result with a GENERATED header. Replaces the P1 alpha behavior of copying
# the monolithic CLAUDE.md verbatim. Bash 3.2 safe.

render_kernel_vars() {
    file="$1"
    SOLAR_HOME="$SOLAR_HOME" CLAUDE_DIR="$CLAUDE_DIR" SOLAR_DB="$SOLAR_DB" \
    python3 - "$file" <<'PY'
import os
import re
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as f:
    text = f.read()

mapping = {
    "SOLAR_HOME": os.environ.get("SOLAR_HOME", ""),
    "CLAUDE_DIR": os.environ.get("CLAUDE_DIR", ""),
    "SOLAR_DB": os.environ.get("SOLAR_DB", ""),
}
# Allow any SOLAR_* env var as a template source (WS3 config vars).
for key, value in os.environ.items():
    if key.startswith("SOLAR_"):
        mapping.setdefault(key, value)


def repl(match):
    key = match.group(1).strip()
    return mapping[key] if key in mapping else match.group(0)


pattern = re.compile(r"\{\{\s*([A-Za-z0-9_]+)\s*\}\}")
text = pattern.sub(repl, text)
leftover = sorted(set(pattern.findall(text)))
if leftover:
    sys.stderr.write("unresolved kernel template vars: %s\n" % ", ".join(leftover))
    raise SystemExit(1)

with open(path, "w", encoding="utf-8") as f:
    f.write(text)
PY
}

# kernel_assemble <output-file> — assemble the kernel into an arbitrary file
# (used both by the installer and by the kernel-gen CI check for min/max
# assemblies). Honors SELECTED_COMPONENTS and SOURCE_DIR.
kernel_assemble() {
    out="$1"
    kernel_dir="$SOURCE_DIR/kernel"
    manifest="$kernel_dir/kernel.manifest"
    [ -f "$manifest" ] || die "kernel manifest missing: $manifest"

    tmp="$out.tmp.$$"
    mkdir -p "$(dirname "$out")"
    {
        printf '# OpenSolar Kernel\n\n'
        printf '<!-- GENERATED by kernel-gen.sh — do not edit directly. Re-run the installer instead. -->\n'
        printf '<!-- components: %s -->\n\n' "$SELECTED_COMPONENTS"
    } > "$tmp"

    while IFS='|' read -r frag req; do
        frag="$(printf '%s' "$frag" | awk '{$1=$1; print}')"
        req="$(printf '%s' "$req" | awk '{$1=$1; print}')"
        case "$frag" in
            ''|'#'*) continue ;;
        esac
        if [ "$req" != "always" ]; then
            contains_word "$req" "$SELECTED_COMPONENTS" || continue
        fi
        frag_path="$kernel_dir/$frag"
        [ -f "$frag_path" ] || die "kernel fragment missing: $frag_path"
        cat "$frag_path" >> "$tmp"
        printf '\n' >> "$tmp"
    done < "$manifest"

    render_kernel_vars "$tmp"
    mv "$tmp" "$out"
}

kernel_gen() {
    dry_run_note "generate $CLAUDE_DIR/solar/SOLAR.md from kernel manifest" && return 0
    kernel_assemble "$CLAUDE_DIR/solar/SOLAR.md"
}
