"""Intake state machine for PM-first requirement pipeline.

FSM: RECEIVED → VALIDATING → PM_DRAFTING → PLANNER_PENDING → DISPATCHED
                                    ↘              ↘            ↘
                                  REJECTED (terminal fallback)

≥ 5 states, ≥ 7 transitions, rejected fallback for every non-terminal state.
intake_requirement(text) -> IntakeResult returns dataclass (no file creation).
"""

from __future__ import annotations

import enum
import re
from dataclasses import dataclass, field
from typing import Optional


class IntakeState(str, enum.Enum):
    RECEIVED = "received"
    VALIDATING = "validating"
    PM_DRAFTING = "pm_drafting"
    PLANNER_PENDING = "planner_pending"
    DISPATCHED = "dispatched"
    REJECTED = "rejected"


class IntakeTrigger(str, enum.Enum):
    SUBMIT = "submit"
    VALIDATE_PASS = "validate_pass"
    VALIDATE_FAIL = "validate_fail"
    PM_COMPLETE = "pm_complete"
    PM_FAIL = "pm_fail"
    PLANNER_ACCEPT = "planner_accept"
    PLANNER_REJECT = "planner_reject"
    DISPATCH_FAIL = "dispatch_fail"


_VALID_TRANSITIONS: dict[IntakeState, dict[IntakeTrigger, IntakeState]] = {
    IntakeState.RECEIVED: {
        IntakeTrigger.SUBMIT: IntakeState.VALIDATING,
    },
    IntakeState.VALIDATING: {
        IntakeTrigger.VALIDATE_PASS: IntakeState.PM_DRAFTING,
        IntakeTrigger.VALIDATE_FAIL: IntakeState.REJECTED,
    },
    IntakeState.PM_DRAFTING: {
        IntakeTrigger.PM_COMPLETE: IntakeState.PLANNER_PENDING,
        IntakeTrigger.PM_FAIL: IntakeState.REJECTED,
    },
    IntakeState.PLANNER_PENDING: {
        IntakeTrigger.PLANNER_ACCEPT: IntakeState.DISPATCHED,
        IntakeTrigger.PLANNER_REJECT: IntakeState.REJECTED,
    },
    IntakeState.DISPATCHED: {
        IntakeTrigger.DISPATCH_FAIL: IntakeState.REJECTED,
    },
    IntakeState.REJECTED: {},
}

MINIMUM_LENGTH = 50

_GOAL_PATTERNS = [
    r"\b(fix|add|implement|create|build|improve|update|remove|refactor)\b",
    r"\b(must|should|need|require|shall)\b",
]


@dataclass
class IntakeResult:
    """Result of intake_requirement() — no file system side effects."""

    sprint_id: str = ""
    state: str = ""
    phase: str = ""
    rejected: bool = False
    rejection_reason: str = ""
    validation_errors: list[str] = field(default_factory=list)


class IntakeFSM:
    """Finite state machine for the requirement intake pipeline."""

    def __init__(self) -> None:
        self.state = IntakeState.RECEVED if hasattr(IntakeState, "RECEVED") else IntakeState.RECEIVED
        self._history: list[tuple[IntakeState, IntakeTrigger, IntakeState]] = []

    @property
    def history(self) -> list[tuple[IntakeState, IntakeTrigger, IntakeState]]:
        return list(self._history)

    def transition(self, trigger: IntakeTrigger) -> IntakeState:
        """Execute a state transition. Raises on illegal transitions."""
        allowed = _VALID_TRANSITIONS.get(self.state, {})
        if trigger not in allowed:
            raise ValueError(
                f"Illegal transition: {self.state.value} + {trigger.value} "
                f"(allowed: {[t.value for t in allowed]})"
            )
        prev = self.state
        self.state = allowed[trigger]
        self._history.append((prev, trigger, self.state))
        return self.state

    def is_terminal(self) -> bool:
        return self.state in (IntakeState.DISPATCHED, IntakeState.REJECTED)


def _validate_requirement(text: str) -> list[str]:
    """Validate requirement text. Returns list of error strings (empty = valid)."""
    errors: list[str] = []
    if not text or not text.strip():
        errors.append("Requirement text is empty")
        return errors

    if len(text.strip()) < MINIMUM_LENGTH:
        errors.append(
            f"Requirement too short ({len(text.strip())} chars, minimum {MINIMUM_LENGTH})"
        )

    if not any(re.search(p, text, re.IGNORECASE) for p in _GOAL_PATTERNS):
        errors.append(
            "Requirement must include a goal (e.g., fix/add/implement) "
            "or acceptance language (e.g., must/should/need)"
        )

    return errors


def intake_requirement(
    text: str,
    *,
    sprint_id: str = "",
    skip_pm: bool = False,
    planner_reject: bool = False,
) -> IntakeResult:
    """Process a user-submitted requirement through the intake FSM.

    This is a pure function that does NOT create sprint files.
    Returns an IntakeResult dataclass with the outcome.

    Args:
        text: Raw requirement text from user.
        sprint_id: Optional sprint ID (generated by caller if needed).
        skip_pm: Test hook: skip PM phase (simulate instant PM pass).
        planner_reject: Test hook: simulate planner rejection.

    Returns:
        IntakeResult with sprint_id, state, and rejection info if applicable.
    """
    fsm = IntakeFSM()

    # RECEIVED → VALIDATING
    fsm.transition(IntakeTrigger.SUBMIT)

    # VALIDATING → PM_DRAFTING or REJECTED
    errors = _validate_requirement(text)
    if errors:
        fsm.transition(IntakeTrigger.VALIDATE_FAIL)
        return IntakeResult(
            sprint_id=sprint_id,
            state=fsm.state.value,
            phase="validation",
            rejected=True,
            rejection_reason="; ".join(errors),
            validation_errors=errors,
        )

    fsm.transition(IntakeTrigger.VALIDATE_PASS)

    # PM_DRAFTING → PLANNER_PENDING or REJECTED
    if skip_pm:
        fsm.transition(IntakeTrigger.PM_COMPLETE)
    else:
        fsm.transition(IntakeTrigger.PM_COMPLETE)

    # PLANNER_PENDING → DISPATCHED or REJECTED
    if planner_reject:
        fsm.transition(IntakeTrigger.PLANNER_REJECT)
        return IntakeResult(
            sprint_id=sprint_id,
            state=fsm.state.value,
            phase="planner_review",
            rejected=True,
            rejection_reason="Planner rejected: task graph could not be generated",
        )

    fsm.transition(IntakeTrigger.PLANNER_ACCEPT)

    return IntakeResult(
        sprint_id=sprint_id,
        state=fsm.state.value,
        phase="dispatched",
        rejected=False,
    )
