"""Error code constants for TUI pane lifecycle (per architecture.md §9.1)."""

PROCEED_PROMPT_STUCK = "PROCEED_PROMPT_STUCK"
QUEUED_PROMPT_STUCK = "QUEUED_PROMPT_STUCK"
PERMISSION_LOOP = "PERMISSION_LOOP"
CLEAR_FAILED_EXHAUSTED = "CLEAR_FAILED_EXHAUSTED"
RESPAWN_FAILED = "RESPAWN_FAILED"

ALL_ERROR_CODES = frozenset({
    PROCEED_PROMPT_STUCK,
    QUEUED_PROMPT_STUCK,
    PERMISSION_LOOP,
    CLEAR_FAILED_EXHAUSTED,
    RESPAWN_FAILED,
})
