import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT / "harness" / "tools"))

import gemini_deep_research_operator as gdro

def test_e2e_successful_run(monkeypatch, tmp_path):
    class Result:
        returncode = 0
        stdout = "E2E Deep Research Report Content"
        stderr = ""

    request_dir = tmp_path / "gemini-deep-research-request"
    request_dir.mkdir(parents=True, exist_ok=True)
    
    # Mock files generated by wrapper
    (request_dir / "assistant-response.txt").write_text("E2E Mock Report", encoding="utf-8")
    (request_dir / "page.json").write_text(json.dumps({
        "title": "E2E Deep Research Title",
        "url": "https://gemini.google.com/app/e2e123",
        "conversation_id": "e2e123",
        "citations": [{"title": "Cite 1", "url": "https://example.com/cite1"}]
    }), encoding="utf-8")

    monkeypatch.setattr(gdro, "_wrapper_cmd", lambda: ["fake-wrapper"])
    monkeypatch.setattr(gdro.subprocess, "run", lambda *args, **kwargs: Result())
    
    result = gdro.run_request({
        "prompt": "E2E Prompt",
        "project_name": "E2E Project",
        "request_dir": str(request_dir)
    }, task_dir=tmp_path)
    
    assert result["ok"] is True
    assert result["text"] == "E2E Mock Report"
    assert result["conversation_id"] == "e2e123"
    assert len(result["citations"]) == 1
    assert result["citations"][0]["title"] == "Cite 1"
